# ![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/50px-Python-logo-notext.svg.png) **Trabajo Práctico 2: Arreglos uni y multidimensionales** ![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/50px-Python-logo-notext.svg.png)

En este trabajo práctico, vamos a trabajar con arreglos uni y multidimensionales en Python. Recuerden crear una copia de este archivo en su ***Google Drive*** para tener permisos de edición.

### **florencia.dias@unahur.edu.ar**

## **Vectores**

Declaración y modificación/acceso usando índices

In [ ]:
import numpy as estructuracomision3

vector = estructuracomision3.zeros(10 , int)
print(vector)

[0 0 0 0 0 0 0 0 0 0]


In [ ]:
import numpy as np # importamos libreria, np hace refencia a numpy.

########### Unidimencionales ###########
print("########### Unidimencionales ###########")

vector = np.zeros(10, int) # declaramos un vector de 10 enteros

print("Vector de ceros")
print(vector) # lo imprimimos

vector[0] = 20 # en la posicion 0 le cargamos un 20
vector[5] = 10 # en la posicion 5 le cargamos un 10
vector[10] = 58 # la posicion 10 no existe, porque llega hasta 9, deberia de dar un error

print("Vector con modificaciones")
print(vector)

Recorrido por los elementos y por los índices

In [ ]:
import numpy as np

vector = np.array([3,5,1,8,14]) # declaramos vector de enteros

print(vector)
print("Recorrido sobre elementos directamente (sentido directo)")
for elemento in vector:
  print(elemento)

print("\n", vector)
print("Recorrido sobre elementos directamente (sentido inverso)")
for elemento in reversed(vector):
  print(elemento)

print("\n", vector)
print("Recorrido usando indices / posiciones (sentido directo)")
for posicion in range(len(vector)): #len de vector es 5, el rango de 0 hasta 4
  print("Posicion: ", posicion) # imprime el valor de posicion (0,1,2,3,4)
  print(vector[posicion]) # imprimi el elemento del vector en esa posicion

print("\n", vector)
print("Recorrido usando indices / posiciones (sentido inverso)")
for posicion in reversed(range(len(vector))):
  print("Posicion: ", posicion)
  print(vector[posicion])

[ 3  5  1  8 14]
Recorrido sobre elementos directamente (sentido directo)
3
5
1
8
14

 [ 3  5  1  8 14]
Recorrido sobre elementos directamente (sentido inverso)
14
8
1
5
3

 [ 3  5  1  8 14]
Recorrido usando indices / posiciones (sentido directo)
Posicion:  0
3
Posicion:  1
5
Posicion:  2
1
Posicion:  3
8
Posicion:  4
14

 [ 3  5  1  8 14]
Recorrido usando indices / posiciones (sentido inverso)
Posicion:  4
14
Posicion:  3
8
Posicion:  2
1
Posicion:  1
5
Posicion:  0
3


Notación para acceder a subvectores

In [ ]:
import numpy as np

arr1 = np.array([4, 3, 5, 8, 6, 5, 7, 5])

print(arr1[1:]) # a partir de la posicion 1
print(arr1[:2]) # accedemos a los primeros 2
print(arr1[len(arr1)-3:]) # ultimos 3
print(arr1[2:6]) # rangos, ojo menos 1
print(arr1[::2]) # saltos

[3 5 8 6 5 7 5]
[4 3]
[5 7 5]
[5 8 6 5]
[4 5 6 7]


Manejo de strings como vectores

In [ ]:
import numpy as np

########### Arreglos de caracteres ###########
print("########### Arreglos de caracteres ###########")

cadena = np.array(["hr","or","l","a"]) # declaramos arreglo de caracteres

print(cadena)
cadena [1] = "f" # modificamos el elemento en posion 1
print(cadena)

########### Tipo Str ###########
print("########### Tipo Str ###########")

cadenaStr = "hola"  # declaramos una variable de tipo str

print(cadenaStr)
print(cadenaStr[0]) # accedemos al elemento en posicion 0, podemos leer

#cadenaStr[1] = "f" # no me deja ya que es inmutable, no se puede modificar, no se puede escribir

########### Arreglos de caracteres ###########
['hr' 'or' 'l' 'a']
['hr' 'f' 'l' 'a']
########### Tipo Str ###########
hola
h


In [ ]:
type(np.array([]))

numpy.ndarray

Cosas a tener en cuenta

In [ ]:
import numpy as np

vector1 = np.array([2,3,6,1])
vector2 = vector1 # nueva refencia que vector 1, pero la posicion en memoria es la misma

print("Vector1 = ", vector1)
print("Vector2 = ", vector2)

print("\nModificamos solo a vector 1")

vector1[1] = 200

print("Vector1 = ", vector1) # si modifico vector 1, modifico vector 2  viceversa
print("Vector2 = ", vector2)

######### solucion
# vector2 = np.zeros((4),int) e ir iterando con un for vector1 e ir copiando elemento a elemento a vector2

Vector1 =  [2 3 6 1]
Vector2 =  [2 3 6 1]

Modificamos solo a vector 1
Vector1 =  [  2 200   6   1]
Vector2 =  [  2 200   6   1]


Arreglos como parametros de funciones / procedimientos

In [ ]:
import numpy as np

def funcionEjemplo(vector): # recibe por parametro un vector
  vector[1] = 20 #lo modifica
  return

v = np.array ([2,5,3,9])

print("v: ", v)

funcionEjemplo(v)

print("\nLuego de ejecutar funcionEjemplo") # paso por referencia, las modificaciones valen afuera de la funcion
print("v: ", v)

v:  [2 5 3 9]

Luego de ejecutar funcionEjemplo
v:  [ 2 20  3  9]


### **Ejercicio 1**

Escribir una función que recibe un numero entero N y le pide al usuario que ingrese N numeros. Al final, el programa debe retornar un vector contiendo los números que fueron ingresados. Tambien debe imprimir por pantalla la suma total de los valores y el promedio. Se deben hacer funciones para resolver el promedio y la suma total.

In [ ]:
import numpy as np
def sumaTotal(vector:np.array)->int:
  suma = 0 #Inicializo la variable "suma" en 0
  for valor in vector: #Para cada valor en el vector:
    suma += valor #suma será el valor que hay en la variable "suma" más el "valor" actual que haya tomado del vector
  return suma #Una vez que termine de iterar devolvemos el valor de la variable "suma"

def promedio(vector:np.array)-> float:
  return sumaTotal(vector)/len(vector) #El promedio es la suma de los elementos dividida la cantidad de elementos

def ingresarEnteros(N:int)->np.array:
  salida = np.zeros(N, int) #Inicializo la salida con un vector de ceros
  for pos in range(len(salida)): #0,1,2,3,4,....,N-1 #Obtengo los índices
    salida[pos] = int(input("Ingrese un numero: ")) #Asigno a cada lugar del vector, un número ingresado por el usuario
  print(sumaTotal(salida)) #Retorno el valor de la suma
  print(promedio(salida)) #Retorno el valor del promedio
  return salida #Retorno el vector ingresado por el usuario

  #Suma iterando por las posiciones
  #for pos in range(len(vector)):
  #  suma += vector[pos]

v = ingresarEnteros(3)
print(v)

### **Ejercicio 2**

Escribir una función que recibe un vector de strings y retorna otro con los mismos elementos del vector de entrada pero en orden inverso.

In [ ]:
def invertirArreglo(vector:np.array)->np.array:
  vectorInvertido = np.zeros(len(vector), str) #Inicializo un vector de ceros
  pos = 0 #Inicializo la variable posición para ir iterando en el vector
  for valor in reversed(vector): #Itero los valores en el vector invertido
    vectorInvertido[pos] = valor #Asigno a mi vector de ceros, para cada lugar, un valor (tomados invertidos del vector original)
    pos += 1 #Incremento mi contador de vector invertido
  return vectorInvertido #Retorno el valor invertido

palabra = np.array(["h","o","l","a","c","o","m","o"])
print(palabra)
print(invertirArreglo(palabra))

['h' 'o' 'l' 'a' 'c' 'o' 'm' 'o']
['o' 'm' 'o' 'c' 'a' 'l' 'o' 'h']


In [ ]:
def invertirArreglo(vector:np.array)->np.array:
  vectorInvertido = np.zeros(len(vector), str) #Inicializo un vector de ceros
  for pos, elemento in enumerate(reversed(vector)): #Itero los valores en el vector invertido
    vectorInvertido[pos] = elemento #Asigno a mi vector de ceros, para cada lugar, un valor (tomados invertidos del vector original)
  return vectorInvertido

In [ ]:
def stringInversor1(stringVector:np.array)->np.array: #Otra forma de pensarlo es invertir los strings, dentro de un vector
  salida = np.zeros(len(stringVector)).astype(str) #Inicializo mi vector de salida con ceros

  for i in range(len(stringVector)): #Itero en lo índices del vector de entrada
    salida[i] = stringVector[i][::-1] #Cada elemento del vector de entrada es un string, que puedo manipular como un vector. Recorro todos los elementos de atrás para adelante

  return salida #Retorno el valor de salida con cada string invertido.

misStrings = np.array(["Hola" , "Mundo" , "Como" , "Estas"])

print(stringInversor1(misStrings))

['aloH' 'odnuM' 'omoC' 'satsE']


In [ ]:
def stringInversor2(stringVector:np.array)->np.array: #Otra forma de hacer la versión que vimos antes:
  salida = np.zeros(len(stringVector)).astype(str) #Inicializo mi vector de salida en cero

  for i in range(len(stringVector)): #Para cada índice en el rango del vector de strings
    salida[i] = stringVector[len(stringVector)-(i+1)] #Asignamos a la salida el último elemento: tamaño del vector menos el índice que estamos recorriendo

  return salida #Devolvemos la salida

print(stringInversor2(misStrings))

['Estas' 'Como' 'Mundo' 'Hola']


### **Ejercicio 3**

Escribir la función sumaDeVectores que recibe dos vectores de enteros del mismo tamaño y retorna otro con la suma de ambos. La suma de vectores se realiza componente a componente, segun la siguiente forma:

v<sub>1</sub> = [ v<sub>11</sub> , v<sub>12</sub> , v<sub>13</sub> , ... , v<sub>1N</sub> ]

v<sub>2</sub> = [ v<sub>21</sub> , v<sub>22</sub> , v<sub>23</sub> , ... , v<sub>2N</sub> ]

v<sub>1</sub> + v<sub>2</sub> = [ v<sub>11</sub> + v<sub>21</sub> , v<sub>12</sub> + v<sub>22</sub> , v<sub>13</sub> + v<sub>23</sub> , ... , v<sub>1N</sub> + v<sub>2N</sub> ]

In [ ]:
def sumaVectores(v1:np.array, v2:np.array)->np.array:
  salida = np.zeros(len(v1), int) #Inicializo mi vector de salida con ceros
  for posicion in range(len(salida)): #Itero sobre los índices
    salida[posicion] = v1[posicion] + v2[posicion] #A cada posición del vector de salida le asigno la suma de ambos vectores
  return salida #Retorno la salida

suma = sumaVectores(np.array([2,3,4,5]),np.array([5,1,2,3]))
print(suma)

[7 4 6 8]


In [ ]:
def sumaDeVectores(vec1:np.array , vec2:np.array)->np.array: #Otra forma de ver lo mismo
  N = len(vec1) #Me interesa N porque es el parámetro de todos mis vectores
  if N != len(vec2): #Valido que los vectores que voy a sumar tengan el mismo tamaño
    raise Exception(f"Los vectores deben tener el mismo Tamaño! vec1 tiene {len(vec1)} elementos y vec2 tiene {len(vec2)}") #lanzo una excepción

  resultado = np.zeros(N) #Inicializo el vector resultado con N ceros

  for i in range(N): #Itero sobre los índices
    resultado[i] = vec1[i] + vec2[i] #Asigno en cada posición la suma de ambos vecores

  return resultado #Retorno el resultado

vec1 = np.array([1 , 2 , 3])
vec2 = np.array([4 , 5 , 6])
#vec3 = np.array([7 , 8 , 9 , 10])

print(sumaDeVectores(vec1 , vec2))
#print(sumaDeVectores(vec2 , vec3))

[5. 7. 9.]


### **Ejercicio 4**

Escribir una función que recibe un vector y desplaza todos sus elementos una posición hacia la derecha: el primero pasa a ser el segundo, el segundo pasa a ser el tercero y así sucesivamente. El último pasa a ser el primero.

Por ejemplo:

v1 = [2, 4, 1, 5, 7, **9**]

**desplazarADerecha(v1)**

=> v1 = [**9**, 2, 4, 1, 5, 7]

In [ ]:
def desplazarADerecha(vector:np.array)->None: #En este caso devuelvo el mismo vector modificado
  ultimo = vector[len(vector)-1] #9 #Tomo el último valor
  for pos in reversed(range(0, len(vector)-1)): #range(0,5) -> 0,1,2,3,4 #Itero sobre los valores menos uno (por  que tengo el último)
    #pos = va desde 4 hasta 0
    vector[pos+1] = vector[pos]  #vector[1] = vector[0] #Muevo todos los números a la derecha
  v[0] = ultimo #Asigno mi último a la posición cero

v = np.array([2, 4, 1, 5, 7, 9])
print(v)
desplazarADerecha(v)
print(v)

[2 4 1 5 7 9]
[9 2 4 1 5 7]


In [ ]:
def desplazarADerecha(vector: np.array)-> None:#Como hacerlo con un vector intermedio
  vectorDesplazado = np.zeros(len(vector), int) #Inicializo mi vector intermedio de ceros
  vectorDesplazado[0] = vector[-1] #Inciailizo el primer elemento de mi vector resultado con
  for pos in range(1, len(vector)): #Para cada índice empezando desde 1, porque el 0 ya lo tengo asignado
        vectorDesplazado[pos] = vector[pos-1] #La posición de ese vector será la posición anterior del vector original (de esta forma desplazo a la derecha)
  for pos in range(len(vectorDesplazado)): #Ahora para cada índice (cualquiera de los dos vectores)
    vector[pos] = vectorDesplazado[pos] #Asigno en mi vector original los valores tal cual del vector intermedio

v1  = np.array([2, 4, 1, 9, 8])
print(v1)
desplazarADerecha(v1)
print(v1)

[2 4 1 9 8]
[8 2 4 1 9]


In [ ]:
def desplazarVectorDer(vector:np.array)->None: #Más compacto
  arrAux = np.array(vector) #copio el vector
  for i in range(len(vector)): #Le asigno a cada posición la posición anterior
    vector[i] = arrAux[i-1]    ###Esta usando la posicion -1 en la primer iteracion

v1  = np.array([2, 4, 1, 9, 8])
print(v1)
desplazarVectorDer(v1)
print(v1)

[2 4 1 9 8]
[8 2 4 1 9]


### **Ejercicio 5**

Desarrollar una función que inserte un elemento en una posición en un vector. Al insertar el elemento, se debe producir un desplazamiento a la derecha de todos los elementos en las posiciones siguientes, el último elemento se pierde.

Por ejemplo:

v1 = [2, 4, 1, 7, 6, 2]

**insertar(v1, 5, 3)** #insertamos un 5 en la posición 3

=> v1 = [2, 4, 1, **5**, 7, 6]

In [ ]:
def insertar(arr, pos, val):
  for i in reversed(range(pos, len(arr)-1)): #Tomo los índices desde la posicion donde quiero insertar hasta el anteúltimo (dado que el último se pierde). Lo invierto (para empezar de atrás hacia adelante)
    print(i+1, i) #Para control veo cuáles son los índices que estoy trabajando
    arr[i+1] = arr[i] #En una primera iteración, i debe ser el anteúltimo elemento. Por lo que i+1 es el último elemento, asigno como último al anteúltimo. Así sigo hast la posición en la que voy a insertar
  arr[pos] = val #una vez llegado tanto pos como pos+1 son el mismo número. Le asigno el valor que quiero insertar

arr1 = np.array([2, 4, 1, 7, 6, 2])
insertar(arr1, 3, 5)
print(arr1)

5 4
4 3
[2 4 1 5 7 6]


In [ ]:
def insertar2(vector:np.array , numero:int , posicion:int)->np.array: #Otra forma de verlo:
  N = len(vector) #Tamaño de mi vector
  for i in range(N-1 , posicion , -1): #Armo un rango desde el anteúltimo índice, hasta la posición que quiero, avanzando de a -1 (para atrás)
    vector[i] = vector[i-1] #Asigno a cada posición, el valor anterior

  vector[posicion] = numero #En la posición de interés agrego el número

  return vector #Retorno el vector

v1 = [2, 4, 1, 7, 6, 2]

print(insertar2(v1 , 5 , 3))

[2, 4, 1, 5, 7, 6]


### **Ejercicio 6**

Escribir una función que elimine el elemento que ocupa una determinada posición de un vector. Al eliminar, los elementos a la derecha del eliminado, deben desplazarse a la izquierda un lugar y agregar un cero en la última posición.

Por ejemplo:

v1 = [4, 3, **5**, 8, 6, 7]

**eliminar(v1, 2)** #eliminamos el elemento de la posicion 2

=> v1 = [4, 3, **8, 6, 7, 0**]

In [ ]:
#v1 = [3, 5, 8, 6, 7, 7] 0 -> len(v1)-2 -> range(0,len(v1)-1)

def eliminar(vector:np.array, posDel:int)->None:
  if 0 <= posDel < len(vector): #Primero valido que la posición a eliminar esté dentro del rango de nuestro vector
    for pos in range(posDel,len(vector)-1): #Para cada posición entre el indice que eliminaremos y el tamaño del vector:
      vector[pos] = vector[pos+1] #Asignamos a cada posición el valor de su derecha
    vector[len(vector)-1] = 0 #Ponemos un cero en la última posición
  else: #En caso que no esté el valor a eliminar dentro del rango:
    raise IndexError("Posicion incorrecta") #Lanzamos un error

v1  = np.array([4, 3, 5, 5, 6, 7])
print(v1)
eliminar(v1,2)
print(v1)
eliminar(v1,2)
print(v1)

[4 3 5 5 6 7]
[4 3 5 6 7 0]
[4 3 6 7 0 0]


### **Ejercicio 7**

Escribir una función que elimine todas las apariciones de un determinado elemento de un vector. Al eliminar se deben insertar tantos ceros al final como elementos se eliminaron.

Por ejemplo:

arr1 = [4, 3, 5, 8, 6, 5, 7, 5]

**eliminarApariciones(arr1, 5)** #eliminamos todos los 5 del arreglo

=> arr1 = [4, 3, 8, 6, 7, **0, 0, 0**]

In [ ]:
#Recorrer array y usar funcion del ejercicio 5 para eliminar los elementos de a uno
def eliminarApariciones(vector:np.array, datoDel:int)->None:
  pos = 0 #Inicializo un contador en cero
  while pos < len(vector): #Mientras el contador sea menor que el tamaño del vector:
    if vector[pos] == datoDel: #Si el elemento de la posición POS coincide con el dato a eliminar:
      eliminar(vector, pos) #Reciclamos el código, llamamos a la función eliminar que lo elimina, desplaza todos los números a la izquierda y agrega un cero en último lugar
    #Notemos acá que si elimina, en la próxima iteración volvemos a ver el mismo lugar porque en POS está el valor que antes estaba a la izquierda
    else:
      pos += 1 #Si el valor no coincide, incrementamos el valor del contador y seguimos iterando
v3 = np.array([4, 3, 5, 8, 6, 5, 7, 5])
print(v3)
eliminarApariciones(v3,5)
print(v3)

[4 3 5 8 6 5 7 5]
[4 3 8 6 7 0 0 0]


### **Ejercicio 8**

Escribir un procedimiento que reciben un vector y:
- Imprime un subvector con los dos primeros elementos.
- Imprime un subvector con los tres últimos elementos.
- Imprime un subvector con los elementos desde la posiciones 2 hasta la 5
- Imprime un subvector con los elementos alternados cada dos. Por ej.: v1 = [2 , 1 , 4 , 5 , 2 , 7 , 9] debería imprimir [2 , 4 , 2 , 9]

Nota: Se debe utilizar la notacion **vector [ pos<sub>inicio</sub> : pos<sub>fin</sub> : paso ]**

In [ ]:
def subVectores(unVector:np.array)->None:
  N = len(unVector) #Guardo el tamaño de mi vector
  subVector1 = unVector[0:2] #Tomo los dos primeros elementos. Recordemos que es [0:2), el 2 no está incluído
  subVector2 = unVector[-3:N] #Tomo los últimos tres elementos (desde -3 hasta N-1)
  subVector3 = unVector[2:5+1] #Tomo los elementos desde el 2 hasta el 5 (dejo explícito que es 5+1 porque el último no está incluído)
  subVector4 = unVector[0:N:2] #Tomo los elementos del primero al último saltando de a dos

  print(f'Los dos primeros elementos son {subVector1}')
  print(f'Los últimos tres elementos son {subVector2}')
  print(f'Los elementos desde la posición 2 hasta la 5 son {subVector3}')
  print(f'Los elementos alternados cada dos son {subVector4}')

  return

v1 = np.array([2 , 1 , 4 , 5 , 2 , 7 , 9])

subVectores(v1)

Los dos primeros elementos son [2 1]
Los últimos tres elementos son [2 7 9]
Los elementos desde la posición 2 hasta la 5 son [4 5 2 7]
Los elementos alternados cada dos son [2 4 2 9]


## **Matrices**

Declaración de matrices y acceso/modificación usando índices

In [ ]:
########### Bidimencionales ###########
print("########### Bidimencionales ###########")

matriz = np.zeros ((3,4), int) #filas y columnas

print("\nMatriz")
print(matriz)

matriz[0][0] = 20
matriz[0][2] = 10
matriz[1][3] = 50

print("Matriz con modificaciones")
print(matriz)
print("Primer fila")
print(matriz[0])
print("Segunda fila")
print(matriz[1])
print("Elemento fila 1, columna 3")
print(matriz[1][3])
print("Columna 3")
print(matriz[:,3])

########### Bidimencionales ###########

Matriz
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Matriz con modificaciones
[[20  0 10  0]
 [ 0  0  0 50]
 [ 0  0  0  0]]
Primer fila
[20  0 10  0]
Segunda fila
[ 0  0  0 50]
Elemento fila 1, columna 3
50
Columna 3
[ 0 50  0]


Recorrido por los elementos

In [ ]:
import numpy as np

matriz = np.array([[3,5,1],[2,8,14],[12,3,9],[23,4,0]]) # generamos matriz de 4 filas y 3 columnas

print(matriz)
print("\nRecorrido sobre elementos directamente (sentido directo)")
for fila in matriz: # en la primera iteracion entra a la primer fila
  for elemento in fila: # fila es un vector
    print(elemento)

print("\n", matriz)
print("Recorrido sobre elementos directamente (sentido inverso)")
for fila in reversed(matriz): # en la primera iteracion entra a la ultima fila
  for elemento in reversed(fila):
    print(elemento)

Recorrido por las posiciones

In [ ]:
print("\n", matriz)
print("Recorrido usando indices / posiciones (sentido directo)")
for posicionFila in range(len(matriz)): #len de matriz es la cantidad de filas, y el  rango es 0,1,2 y 3
  for posicionColumna in range(len(matriz[posicionFila])): # para cada fila hacemos un rango por columnas, 0,1 y 2
    print("Posicion:", posicionFila,",", posicionColumna)
    print(matriz[posicionFila][posicionColumna])

print("\n", matriz)
print("Recorrido usando indices / posiciones (sentido inverso)")
for posicionFila in reversed(range(len(matriz))): #
  for posicionColumna in reversed(range(len(matriz[posicionFila]))):
    print("Posicion:", posicionFila,",", posicionColumna)
    print(matriz[posicionFila][posicionColumna])

Notación para acceder a submatrices

In [ ]:
import numpy as np

matriz = np.array([[3,5,1],[2,8,14],[12,3,9],[23,4,0]])

print(matriz[0:2]) # primeras 2 filas

print(matriz[0:4:2]) #con saltos

[[ 3  5  1]
 [ 2  8 14]]
[[ 3  5  1]
 [12  3  9]]


Medicion de mediciones

In [ ]:
print("Cantidad de filas")
print(len(matriz))

print("Cantidad de columnas")
print(len(matriz[0]))

print("Dimension de matriz")
print(matriz.shape)

(filas,columnas) = matriz.shape # en dos variables distintas
print(filas)
print(columnas)

Cantidad de filas
4
Cantidad de columnas
3
Dimension de matriz
(4, 3)
4
3


### **Ejercicio 12**

Escribir una función que recibe las dimensiones y retorna una matriz rellena de la siguiente forma: En la posición ( n , m ) debe contener n + m.

Por ejemplo:

mat1 = rellenaMatriz(4,3)

=> mat1 =

| <!--   --> |Col 0|Col 1|Col 2|
|------------|:---:|:---:|:---:|
| **Fila 0** |  0  |  1  |  2  |
| **Fila 1** |  1  |  2  |  3  |
| **Fila 2** |  2  |  3  |  4  |
| **Fila 3** |  3  |  4  |  5  |

In [ ]:
def rellenaMatriz(nFilas:int, nCols:int)->np.array: #Definimos una función que toma un número de filas, un número de columnas y devuelve un array
  matrizSalida = np.zeros((nFilas,nCols), int) #Inicializo mi matriz como un arreglo de ceros (enteros) con los valores que le pasé por parámtero
  for nFila in range(nFilas): #Para cada número de fila en mi rango de número de filas:
    for nCol in range(nCols): #Para cada número de columna en mi rango de número de columnas:
      matrizSalida[nFila, nCol] = nFila+nCol #La matriz de salida en la ubicación "número de fila" "número de columna" será número de fila + número de columna
      # también podíamos hacer:
      # matrizSalida[nFila][nCol] = nFila+nCol
  return matrizSalida #Retornamos la matriz de salida

print(rellenaMatriz(4,3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


### **Ejercicio 13**

Escribir una función que recibe una matriz cuadrada (N x N) y calcula la suma de los elementos que están por encima de la diagonal principal (excluyendo la diagonal).

En el ejemplo de la imagen, la función deberia retornar: *b + c + f*

![texto alternativo](https://economipedia.com/wp-content/uploads/Captura-de-Pantalla-2019-07-29-a-les-13.18.05-1.png)

In [ ]:
#nCol > nFila -> triangulo superior
#nCol == nFila -> diagonal pricipal
#nCol < nFila -> triangulo inferior

def suma_encima_diagonal(matriz): #Mi función toma como parámetro una matriz. Retorna un valor
  suma = 0 #Inicializo el valor de salida en cero
  nFilas, nCols = matriz.shape  #3,3 #es un PREREQUISITO que la matriz sea cuadrada, en este caso nFilas = nCols
  for posFila in range(nFilas): #0,1,2 #Para cada fila en el rango de filas
    for posCol in range(posFila+1, nCols): #range(2,3) -> 2 # Para cada columna en el rango de filas + 1 hasta nCols (es decir, no me interesan las columnas que sean menores que las filas)
      suma += matriz[posFila,posCol] #Sumo a mi valor de salida el valor alojado en esa posición
  return suma #Devolvemos el valor

def sumaTsuperior(matriz:np.array)->int:
  suma = 0
  nFilas, nCols = matriz.shape  #3,3
  for posFila in range(nFilas): #0,1,2
    for posCol in range(nCols): #0,1,2
      if posCol > posFila:
        suma += matriz[posFila,posCol]
  return suma

matriz = np.array([[1 , 2 , 3 , 4] , [4 , 5 , 6 , 7] , [7 , 8 , 9 , 10] , [11 , 12 , 13 , 14]])
print(matriz)
print(suma_encima_diagonal(matriz))
print(sumaTsuperior(matriz))

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]
 [11 12 13 14]]
32
32


In [ ]:
#Otra forma de verlo:

def sumaTriangularSuperior(matrizCuadrada:np.matrix)->int:
  N = len(matrizCuadrada) #Como la matriz es cuadrada es lo mismo pedir len o shape
  suma = 0 #Inicializo me falor de salida
  for fila in range(N-1): #Recorro todas las filas menos la última, porque es triangular superior.
    suma += matrizCuadrada[fila][fila + 1:].sum() # De cada fila, me quedo con los valores de la derecha del número de fila, es decir, con la triangular superior. Eso es un arreglo, del cual puedo sumar sus elementos.

  return suma #Devuelvo el valor de la suma

print(sumaTriangularSuperior(matriz))

32


### **Ejercicio 14**

Escribir una función que retorna *True* si una matriz cuadrada es matriz diagonal y *False* en caso contrario.

Una matriz cuadrada diagonal es una matriz que tiene ceros en todos sus elementos, menos en la diagonal principal (No importan los elementos de la diagonal principal, pueden ser cero o no).

**Si i, j son los índices de las filas y columnas de M**

**=> Una matriz M es diagonal si:**

**M [ i , j ] == 0 para todo i != j**

Matriz diagonal de 4 x 4:

| <!--   --> |Col 0|Col 1|Col 2|Col 3|
|------------|:---:|:---:|:---:|:---:|
| **Fila 0** |  0  |  0  |  0  |  0  |
| **Fila 1** |  0  |  2  |  0  |  0  |
| **Fila 2** |  0  |  0  |  4  |  0  |
| **Fila 3** |  0  |  0  |  0  |  0  |

In [ ]:
def esDiagonal1(unaMatrizCuadrada:np.matrix)->bool:#Tomo una matriz cuadrada y devuelvo un valor booleano
  filas , columnas = unaMatrizCuadrada.shape #tomo la cantidad de filas y de columnas

  if filas != columnas: #Valido que la matriz sea cuadrada
    raise Exception('La matriz debe ser cuadrada!') #Lanzo una excepción en caso que no sea cuadrada

  N = filas #Podría ser columnas también, porque es cuadrada

  nElementos = N*(N-1) #La cantidad de elementos que me interesan validar son N al cuadrado (elementos totales del arreglo) menos los elementos de la diagonal, que son N, entonces: nElem = N**2-N = N*(N-1)
  elementosNulos = 0 #Inicializo un contador de elementos nulos. Espero al final de recorrer todo tener la misma cantidad de elemetnos nulos que elementos totales.

  for fila in range(N): #Para cada fila en el rango de filas
    for columna in range(N): #Para cada columna en el rango de columnas
      if fila == columna: #Si el número de fila es igual al número de columna
        pass #No me importa qué sucede
      elif fila != columna and unaMatrizCuadrada[fila][columna] == 0: #Si el número de fila es distinto al de la columna y ese elemento de matriz es nulo
        elementosNulos += 1 #Sumo uno a mis elementos nulos

  return elementosNulos == nElementos #Al final comparo si el número de elementos nulos es igual al número total de elementos fuera de la diagonal.

m1 = np.array([[1 , 2 , 3] , [4 , 5 , 6] , [7 , 8 , 9]])
m2 = np.array([[1 , 0 , 0] , [0 , 5 , 0] , [0 , 0 , 9]])
m3 = np.array([[1 , 0 , 0] , [0 , 5 , 0] , [7 , 0 , 9]])
m4 = np.array([[0 , 0 , 0] , [0 , 0 , 0] , [0 , 0 , 0]])

print(m1)
print(esDiagonal1(m1))
print(m2)
print(esDiagonal1(m2))
print(m3)
print(esDiagonal1(m3))
print(m4)
print(esDiagonal1(m4))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
False
[[1 0 0]
 [0 5 0]
 [0 0 9]]
True
[[1 0 0]
 [0 5 0]
 [7 0 9]]
False
[[0 0 0]
 [0 0 0]
 [0 0 0]]
True


In [ ]:
#Otra forma de verlo
def esDiagonal2(matrizCuadrada:np.array)->bool: #Defino mi función que tomará una matriz cuadrada y devolverá un booleano
  matrizD = True #Inicializo mi valor de salida en True
  nFilas, nCols = matrizCuadrada.shape #Me guardo las dimensiones de filas y columnas. COmo suponemos que la matriz es cuadrada tanto nFilas como nCols debe ser el mismo número
  nFila = 0 #Inicializo un contador
  while matrizD and nFila < nFilas-1: #Mientras matrizD sea True y nFila sea menor al número máximo de filas - 1:
    nCol = nFila+1 #El número de columna será el número de fila + 1. Con esto me aseguro de no pasar por la diagonal pues la fila será seimpre más grande que la columna por construcción
    while matrizD and nCol < nCols: #Mientras matrizD sea True y el número de columna sea menos al número máximo de columnas:
      if matrizCuadrada[nFila,nCol]!=0 or matrizCuadrada[nCol,nFila]!=0: #Si el elemento es distinto de cero tanto arriba como abajo de la diagonal (espejado)
        matrizD = False #Entonces la matriz no es diagonal
      nCol += 1 #Aumento el contador de columna
    nFila += 1 #Aumento el contador de fila
  return matrizD #Retorno el valor de verdad


m = np.array([[1,0,0,0],
              [0,1,0,0],
              [10,0,1,0],
              [0,0,0,1]])
esDiagonal2(m)
print(m1)
print(esDiagonal2(m1))
print(m2)
print(esDiagonal2(m2))
print(m3)
print(esDiagonal2(m3))
print(m4)
print(esDiagonal2(m4))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
False
[[1 0 0]
 [0 5 0]
 [0 0 9]]
True
[[1 0 0]
 [0 5 0]
 [7 0 9]]
False
[[0 0 0]
 [0 0 0]
 [0 0 0]]
True


### **Ejercicio 15**

Escribir una función que retorna *True* si una matriz cuadrada de enteros es simétrica y *False* en caso contrario.

Una matriz simétrica es como la de la imagen (no importan los elementos de la diagonal principal):

![texto alternativo](https://economipedia.com/wp-content/uploads/Captura-de-Pantalla-2019-09-23-a-les-15.58.25.png)

Es decir:

**Si i, j son los índices de las filas y columnas de M**

**=> Una matriz M es simétrica si:**

**M [ i , j ] == M[ j, i ] para todo i != j**

Matriz simétrica de 4 x 4:

| <!--   --> |Col 0|Col 1|Col 2|Col 3|
|------------|:---:|:---:|:---:|:---:|
| **Fila 0** |  2  |  1  |  0  |  5  |
| **Fila 1** |  1  |  2  |  9  |  7  |
| **Fila 2** |  0  |  9  |  0  |  8  |
| **Fila 3** |  5  |  7  |  8  |  4  |

In [ ]:
def esSimetrica(unaMatrizCuadrada:np.matrix)->bool:
  filas , columnas = unaMatrizCuadrada.shape

  if filas != columnas:
    raise Exception('La matriz debe ser cuadrada!') #Lanzo una excepción si la matriz no es cuadrada

  N = filas #Podría ser columnas también
  nElementos = N*(N-1)/2 #Elementos en el triangulo superior o inferior. Se puede demostrar por inducción que N*(N-1) es siempre par
  elementosSimetricos = 0 #Inicializo el contador de elementos simétricos

  for fila in range(N): #Para cada fila en el rango de filas
    for columna in range(N): #Para cada columna en el rango de columnas
      if fila < columna and unaMatrizCuadrada[fila][columna] == unaMatrizCuadrada[columna][fila]: #Si el número de fila es menor que el número de columna (triangulo superior) y los elementos de matriz espejados son iguales:
        elementosSimetricos += 1 #Entonces sumo una unidad de elementos simétricos

  return elementosSimetricos == nElementos #Devuelvo si todos mis elementos son elementos simétricos


m1 = np.array([[1 , 2 , 3] , [4 , 5 , 6] , [7 , 8 , 9]])
m2 = np.array([[1 , 0 , 0] , [0 , 5 , 0] , [0 , 0 , 9]])
m3 = np.array([[1 , 0 , 7] , [0 , 5 , 0] , [7 , 0 , 9]])
m4 = np.array([[0 , 0 , 0] , [0 , 0 , 0] , [0 , 0 , 0]])

print(m1)
print(esSimetrica(m1))
print(m2)
print(esSimetrica(m2))
print(m3)
print(esSimetrica(m3))
print(m4)
print(esSimetrica(m4))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
False
[[1 0 0]
 [0 5 0]
 [0 0 9]]
True
[[1 0 7]
 [0 5 0]
 [7 0 9]]
True
[[0 0 0]
 [0 0 0]
 [0 0 0]]
True


In [ ]:
#Otra forma de verlo:
def esSimetrica(matriz:np.array)->bool: #Tomamos una matriz cuadrada y devolvemos un valor booleano
  matrizEsSimetrica = True #Inicializamos la variable de salida
  nFilas, nCols = matriz.shape #Guardamos las dimensiones
  for nFila in range(nFilas): #Para cada número de fila en el rango de filas
    for nCol in range(nCols): #Para cada número de columna en el rango de columnas
      if matriz[nFila,nCol] != matriz[nCol,nFila]: #Si los elementos de matriz espejados respecto de la diagonal no coinciden:
        matrizEsSimetrica = False #Entonces la matriz no es simétrica

  return matrizEsSimetrica #Devuelvo la conclusión

m=np.array([[2,1,0,5],
            [1,2,9,7],
            [0,9,0,8],
            [5,7,8,4]])
print(esSimetrica(m))

#m[1,2] = m[1][2]

True
